### ISSUE TITLE
Allow effortlessly switching servers

### ISSUE THREAD

**Issue by icarusinthewings** [micahlt/modchat-vue#2]
Hi!
I noticed that one is able to host their own server with modchat-server.
Although that is most likely just for development tests, it would be nice if there was an advanced option in the UI that allows users to change the URL of the server temporarily.  This is probably  a low priority feature, but it would just help open up modchat even more for tinkerers & coders.

**Comment by micahlt** [comment]
This is actually a really good idea!  This would make testing a little easier for those who don't have totally unlimited access to their systems.  The only downside I would think would be fracturing of the community.  People would begin to start their own servers and invite people to join.  That makes Modchat much less useful.  Thoughts?

**Comment by icarusinthewings** [comment]
I would just make it a hidden preference that you need to set every time you load the page. It could be hidden under advanced settings or something. In addition, I think that there should be "Spaces" which are like groups of rooms to make a community. I don't think that fracturing would become that much of a problem and it could only be turned on during development.

**Comment by icarusinthewings** [comment]
Also, (off-topic) Like my new branding?

**Comment by micahlt** [comment]
> hidden preference that you need to set every time you load the page

This won't really work because whenever you use the Vue CLI to develop, any changes you make will force at least a partial reload.  It's impractical to have to paste in the server link over and over.  I think it might be best at this point just to keep server changes down to environment variables.  Changing the envs is pretty simple and most people (even those using Repl.it) can set them very easily.  

> Like my new branding?

Looks a little more like "Jo" than "Jb", but looks nice!
